version: '3.2'

services:
  zookeeper:
    image: zookeeper

  nimbus:
    image: storm
    command: storm nimbus
    depends_on:
      - zookeeper
    ports:
      - 6627:6627
    volumes:
      - './storm-nimbus:/theproject'

  supervisor:
    image: storm
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper

  ui:
    image: storm
    command: storm ui
    depends_on:
      - nimbus
      - zookeeper
      - supervisor
    ports:
      - 8080:8080
