version: '3.2'

services:
  zookeeper:
    image: zookeeper
    ports:
      - 8081:8080

  nimbus:
    image: storm
    command: storm nimbus
    depends_on:
      - zookeeper
    ports:
      - 6627:6627
    volumes:
      - './storm-nimbus:/theproject'

  ui:
    image: storm
    command: storm ui
    depends_on:
      - nimbus
      - zookeeper
    ports:
      - 8080:8080

  supervisor:
    image: storm
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
